sudo: required
services: docker
language: generic
env:
  - DOCKER_FILE=".docker/Dockerfile.ubuntu16.10.py2" PYTHON="python2"
  - DOCKER_FILE=".docker/Dockerfile.ubuntu16.10.py3" PYTHON="python3"

before_install:
  - docker build -t myimage -f "$DOCKER_FILE" .

before_script:
  - docker run --volume "$(pwd):/app" --workdir "/app" --tty --detach myimage bash > container_id

script:
  - docker exec "$(cat container_id)" "$PYTHON" -m pytest
  - docker exec "$(cat container_id)" "$PYTHON" -m flake8

after_script:
  - docker stop "$(cat container_id)"
